export const OFFERLIST_REQUEST = 'OFFERLIST_REQUEST'
export const OFFERLIST_SUCCESS = 'OFFERLIST_SUCCESS'
export const OFFERLIST_FAILURE = 'OFFERLIST_FAILURE'

export const DELETE_OFFER = 'DELETE_OFFER'
export const UPDATE_OFFER = 'UPDATE_OFFER'
export const CREATE_OFFER = 'CREATE_OFFER'
